# Generated by Django 5.0.4 on 2024-06-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Chat',
        ),
    ]
