# Generated by Django 5.0.2 on 2024-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, upload_to='messages/'),
        ),
    ]
