# Generated by Django 5.0.2 on 2024-04-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_profile_topics_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
