# Generated by Django 5.0.2 on 2024-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
