# Generated by Django 5.0.2 on 2024-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_message_author_alter_message_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='icon_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
