# Generated by Django 5.0.4 on 2024-06-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_chapter_topic_chapter_model_chapter_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='chapter_model',
            new_name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='topics',
        ),
    ]
