# Generated by Django 5.0.2 on 2024-04-22 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_profile_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='progect\\django_project\\ForumSite\x0corum\\Image'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
