# Generated by Django 5.0.2 on 2024-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_chapter_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='icon_img',
            field=models.ImageField(upload_to='image_for_site/'),
        ),
    ]
