# Generated by Django 5.0.2 on 2024-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_message_topic_alter_message_image_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(upload_to='messages/'),
        ),
    ]
