# Generated by Django 5.0.2 on 2024-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_chapter_icon_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='icon_img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
