# Generated by Django 5.0.2 on 2024-05-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_chapter_icon_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='chapter',
            field=models.ManyToManyField(to='forum.chapter'),
        ),
    ]
