# Generated by Django 5.0.2 on 2024-05-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_remove_chapter_topics_topic_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=25)),
                ('topic', models.ManyToManyField(to='forum.topic')),
            ],
        ),
    ]
