# Generated by Django 5.0.2 on 2024-05-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text_question',
            field=models.CharField(max_length=70),
        ),
    ]
