# Generated by Django 5.0.2 on 2024-05-16 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_question_text_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='views',
            name='topic',
        ),
        migrations.AddField(
            model_name='message',
            name='question',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='views',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.question'),
            preserve_default=False,
        ),
    ]
